# **SK-Learn Öznitelik Bulma**

In [78]:
metin = {
    "Domates Biber Patlıcan",
    "Patatesli Patlıcan Oturtma",
    "Bir Adet Patlıcan",
    "Bir Orta Boy Patlıcan",
}


In [79]:
text = {
    "I am Optimus Prime, and I send this message to any surviving Autobots taking refuge among the stars",
    "We are here",
    "We are waiting",
    "I am Optimus Prime, and this message is to my Creators",
    "Leave planet Earth alone",
    "Because I am coming for you"
}

## Count Vectorizer

In [80]:
from sklearn.feature_extraction.text import CountVectorizer

In [81]:
cv = CountVectorizer()

In [82]:
cv.fit_transform(metin)

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [83]:
cv.fit_transform(metin).todense()

matrix([[0, 1, 0, 0, 1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 1],
        [0, 0, 1, 1, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1]], dtype=int64)

In [84]:
seyrek = cv.fit_transform(metin)
# Sparse Matrix = Seyrek Matris

In [85]:
seyrek.todense()

matrix([[0, 1, 0, 0, 1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 1],
        [0, 0, 1, 1, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1]], dtype=int64)

In [86]:
cv.vocabulary_

{'domates': 4,
 'biber': 1,
 'patlıcan': 8,
 'bir': 2,
 'adet': 0,
 'orta': 5,
 'boy': 3,
 'patatesli': 7,
 'oturtma': 6}

---
## Stopwords

In [87]:
cv.fit_transform(text)

<6x31 sparse matrix of type '<class 'numpy.int64'>'
	with 41 stored elements in Compressed Sparse Row format>

In [88]:
sparse = cv.fit_transform(text)
sparse_mat = sparse.todense()

In [89]:
sparse_mat

matrix([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
         0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
        [0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [90]:
cv.vocabulary_

{'leave': 14,
 'planet': 18,
 'earth': 10,
 'alone': 0,
 'am': 1,
 'optimus': 17,
 'prime': 19,
 'and': 3,
 'this': 26,
 'message': 15,
 'is': 13,
 'to': 27,
 'my': 16,
 'creators': 9,
 'send': 21,
 'any': 4,
 'surviving': 23,
 'autobots': 6,
 'taking': 24,
 'refuge': 20,
 'among': 2,
 'the': 25,
 'stars': 22,
 'we': 29,
 'are': 5,
 'waiting': 28,
 'here': 12,
 'because': 7,
 'coming': 8,
 'for': 11,
 'you': 30}

In [91]:
sparse_mat.shape

(6, 31)

In [92]:
cv = CountVectorizer(stop_words="english")

In [93]:
stoplu = cv.fit_transform(text).todense()

In [94]:
stoplu

matrix([[0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [95]:
stoplu.shape

(6, 15)

In [96]:
cv.vocabulary_

{'leave': 4,
 'planet': 7,
 'earth': 3,
 'optimus': 6,
 'prime': 8,
 'message': 5,
 'creators': 2,
 'send': 10,
 'surviving': 12,
 'autobots': 0,
 'taking': 13,
 'refuge': 9,
 'stars': 11,
 'waiting': 14,
 'coming': 1}

---
## TF - IDF Transform

In [97]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer

In [98]:
text

{'Because I am coming for you',
 'I am Optimus Prime, and I send this message to any surviving Autobots taking refuge among the stars',
 'I am Optimus Prime, and this message is to my Creators',
 'Leave planet Earth alone',
 'We are here',
 'We are waiting'}

In [99]:
cv

CountVectorizer(stop_words='english')

In [100]:
cv = CountVectorizer()

In [101]:
kelime_say = cv.fit_transform(text)

In [102]:
kelime_say

<6x31 sparse matrix of type '<class 'numpy.int64'>'
	with 41 stored elements in Compressed Sparse Row format>

In [104]:
tfidf_transformer = TfidfTransformer()

In [106]:
tfidf = tfidf_transformer.fit_transform(kelime_say)

In [107]:
tfidf.todense()

matrix([[0.5       , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.5       , 0.        , 0.        , 0.        , 0.5       ,
         0.        , 0.        , 0.        , 0.5       , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.25256388, 0.        , 0.29915105, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.36481199,
         0.        , 0.        , 0.        , 0.36481199, 0.        ,
         0.29915105, 0.36481199, 0.29915105, 0.        , 0.29915105,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.29915105, 0.29915105, 0.        , 0.        ,
         0.        ],
        [0.        , 0.18832708, 0.27202615, 0.22306534, 0.27202615,
         0.        , 0.27202615, 0.        , 0.        , 0.

### Pipeline

In [108]:
from sklearn.pipeline import Pipeline

In [109]:
boru = Pipeline([("cv", CountVectorizer()),("tfidf",TfidfTransformer())])

In [110]:
final_matrix = boru.fit_transform(text)
final_matrix

<6x31 sparse matrix of type '<class 'numpy.float64'>'
	with 41 stored elements in Compressed Sparse Row format>

In [111]:
final_matrix.todense()

matrix([[0.5       , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.5       , 0.        , 0.        , 0.        , 0.5       ,
         0.        , 0.        , 0.        , 0.5       , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.25256388, 0.        , 0.29915105, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.36481199,
         0.        , 0.        , 0.        , 0.36481199, 0.        ,
         0.29915105, 0.36481199, 0.29915105, 0.        , 0.29915105,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.29915105, 0.29915105, 0.        , 0.        ,
         0.        ],
        [0.        , 0.18832708, 0.27202615, 0.22306534, 0.27202615,
         0.        , 0.27202615, 0.        , 0.        , 0.

---
## TF - IDF Vectorizer

In [112]:
tfidf = TfidfVectorizer()

In [113]:
en_final_matris = tfidf.fit_transform(text)

In [114]:
en_final_matris.todense()

matrix([[0.5       , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.5       , 0.        , 0.        , 0.        , 0.5       ,
         0.        , 0.        , 0.        , 0.5       , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.25256388, 0.        , 0.29915105, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.36481199,
         0.        , 0.        , 0.        , 0.36481199, 0.        ,
         0.29915105, 0.36481199, 0.29915105, 0.        , 0.29915105,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.29915105, 0.29915105, 0.        , 0.        ,
         0.        ],
        [0.        , 0.18832708, 0.27202615, 0.22306534, 0.27202615,
         0.        , 0.27202615, 0.        , 0.        , 0.

# **https://www.youtube.com/watch?v=2CIXYQlm2Ho**

# Bu da benden https://www.youtube.com/watch?v=iEUDfS6fMwY